version: "3"
services:

  product-ads:
    build: ./product-ads
    image: prashantpro/product-ads:1.0
    ports:
      - 8081:9080

  product-catalogs:
    build: ./product-catalogs
    image: prashantpro/product-catalogs:1.0
    ports:
      - 8080:9080
      - 9443:9443