##################################################################################################
# Movie Cloud service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: movie-cloud
  labels:
    app: movie-cloud
spec:
  type: NodePort
  selector:
    app: movie-cloud
  ports:
    - port: 8080
      name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-cloud
  labels:
    app: movie-cloud
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-cloud
  template:
    metadata:
      labels:
        app: movie-cloud
        version: v1
    spec:
      containers:
      - name: movie-cloud
        image: quarkus/movie-cloud-jvm:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: movie-config
      restartPolicy: Always
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-config
  namespace: default
data:
  brand.title: MovieTaste
  movie.limit: "4"
