version: '3'
services:
  movie-cloud:
    build: ./movie-cloud
    image: "org.jakartaeeprojects/movie-cloud:1"
    ports:
     - "8080:8080"
  
  recommendation:
    build: ./recommendation
    image: "org.jakartaeeprojects/recommendation:1"
