version: '3'
services:
  movie-cloud:
    build: ./movie-cloud
    image: "org.jakartaeeprojects/movie-cloud:1"
    depends_on: 
      - recommendation
    ports:
     - "9080:9080"
  
  recommendation:
    build: ./recommendation
    image: "org.jakartaeeprojects/recommendation:1"
